sudo: required
services:
    - docker

before_install:
    - docker build -t amizanali/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run amizanali/react-test npm test -- --coverage

after_success:
    - docker build -t amizanali/multi-client ./client
    - docker build -t amizanali/multi-nginx ./nginx
    - docker build -t amizanali/multi-server ./server
    - docker build -t amizanali/multi-worker ./worker
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push to docker hub
    - docker push amizanali/multi-client
    - docker push amizanali/multi-nginx
    - docker push amizanali/multi-server
    - docker push amizanali/multi-worker


deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-245314155649
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY